dubbo:
  application:
    registryUrl:
    name:
    owner:
    enabled:
  #### Provider 配置
  provider:
    enable:
    timeout:
  protocol:
    port:
  #### Consumer 配置
  consumer:
    enable:
    protocol:
    timout: