########## 单表配置方案
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.235:3306/dmall_refund
    username: root
    password: 111111
    ### druid
    initialSize: 19
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j

  ########## REDIS配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host:
    # Redis服务器连接端口
    port:
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 30000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      maxActive: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxWait: -1
      # 连接池中的最大空闲连接
      maxIdle: 8
      # 连接池中的最小空闲连接
      minIdle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描 多个package用","或";"分隔
  type-aliases-package: com.baomidou.mybatisplus.samples.crud.entity
  type-handlers-package:
  global-config:
    db-config:
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断",NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
  1